export const shopContent = {
  brand: {
    name: "Bootlabs",
    siteUrl: "https://bootlabs.de",
    email: "info@bootlabs.de",
  },
  meta: {
    title: "Bootlabs Shop · Gaming-PCs & Hardware",
    description:
      "Vorkonfigurierte und frei konfigurierbare Gaming-PCs, Zubehör und Service — gebaut und betreut von Bootlabs.",
  },
  nav: [
    { label: "Shop", href: "/store" },
    { label: "Konto", href: "/account" },
  ],
  headerCta: {
    label: "Warenkorb",
    href: "/cart",
  },
  hero: {
    kicker: "SHOP",
    line1Prefix: "PCs, die",
    rotating: [
      "einfach laufen.",
      "nicht diskutieren.",
      "sofort einsatzbereit sind.",
      "auch morgen noch laufen.",
    ],
    line2: "Gebaut, getestet, geliefert.",
    support:
      "Vorkonfigurierte Systeme oder frei zusammengestellt. Festpreis nach Konfiguration, Versand in Deutschland, Ansprechpartner statt Ticketschlange.",
    primaryCta: { label: "Zum Shop", href: "/store" },
    secondaryCta: { label: "Konto", href: "/account" },
    facts: [
      "Konfiguriert in Deutschland",
      "Festpreis nach Auswahl",
      "Rückmeldung am selben Tag",
    ],
    terminal: {
      title: "bootlabs@shop: ~",
      command: "bootlabs shop status",
      rows: [
        { label: "gaming-pcs", value: "in vorbereitung" },
        { label: "zubehör", value: "in vorbereitung" },
        { label: "servicepakete", value: "verfügbar" },
        { label: "konfigurator", value: "folgt" },
      ],
      loadLabel: "katalog diese woche",
      loadHint: "phase 0 · fundament",
    },
  },
  ticker: [
    "GAMING-PC",
    "KONFIGURATOR",
    "SSD & RAM",
    "DISPLAY & AKKU",
    "VERSAND DE",
    "FESTPREIS",
    "IT-BETREUUNG",
    "EIGENE SOFTWARE",
  ],
  footer: {
    note: "© 2026 Bootlabs · Software & Hardware",
    links: [
      { label: "bootlabs.de", href: "https://bootlabs.de" },
      { label: "Impressum", href: "/impressum" },
      { label: "Datenschutz", href: "/datenschutz" },
    ],
  },
  legal: {
    email: "info@bootlabs.de",
    siteUrl: "https://bootlabs.de",
    lastUpdated: "2026-09-04",
  },
} as const

export const copy = {
  menu: "Menü",
  home: "Start",
  shop: "Shop",
  account: "Konto",
  cart: "Warenkorb",
  cartWithCount: (count: number) => `Warenkorb (${count})`,
  allProducts: "Alle Produkte",
  viewAll: "Alle anzeigen",
  addToCart: "In den Warenkorb",
  selectVariant: "Variante wählen",
  outOfStock: "Nicht vorrätig",
  selectOptions: "Optionen wählen",
  select: (title: string) => `${title} wählen`,
  from: "ab ",
  original: "Statt: ",
  sortBy: "Sortieren",
  latestArrivals: "Neueste",
  priceLowHigh: "Preis: aufsteigend",
  priceHighLow: "Preis: absteigend",
  option: "Option",
  productInformation: "Produktinformationen",
  shippingReturns: "Versand & Rückgabe",
  material: "Material",
  countryOfOrigin: "Herkunftsland",
  type: "Typ",
  weight: "Gewicht",
  dimensions: "Maße",
  fastDelivery: "Schneller Versand",
  fastDeliveryBody:
    "Dein Paket kommt in 3–5 Werktagen an die Abholstation oder zu dir nach Hause.",
  simpleExchanges: "Einfacher Austausch",
  simpleExchangesBody:
    "Passt etwas nicht? Wir tauschen das Produkt gegen ein neues.",
  easyReturns: "Einfache Rückgabe",
  easyReturnsBody:
    "Schick das Produkt zurück, wir erstatten den Kaufpreis. Ohne Diskussion.",
  relatedProducts: "Ähnliche Produkte",
  relatedProductsBody: "Das könnte ebenfalls passen.",
  emptyCartTitle: "Warenkorb",
  emptyCartBody:
    "Dein Warenkorb ist noch leer. Schau im Shop vorbei und suche dir etwas aus.",
  exploreProducts: "Produkte ansehen",
  alreadyHaveAccount: "Schon ein Konto?",
  signInBetter: "Melde dich an, dann geht der Checkout schneller.",
  signIn: "Anmelden",
  goToCheckout: "Zur Kasse",
  summary: "Zusammenfassung",
  item: "Artikel",
  quantity: "Menge",
  quantityLabel: (qty: number) => `Menge: ${qty}`,
  remove: "Entfernen",
  subtotalExclTax: "Zwischensumme (ohne Steuer)",
  subtotalExclShippingTax: "Zwischensumme (ohne Versand und Steuer)",
  shipping: "Versand",
  discount: "Rabatt",
  taxes: "Steuern",
  total: "Gesamt",
  goToCart: "Zum Warenkorb",
  emptyBag: "Dein Warenkorb ist leer.",
  goToAllProducts: "Zur Produktübersicht",
  backToCart: "Zurück zum Warenkorb",
  back: "Zurück",
  inYourCart: "In deinem Warenkorb",
  shippingAddress: "Lieferadresse",
  billingAddress: "Rechnungsadresse",
  edit: "Bearbeiten",
  delivery: "Lieferung",
  shippingMethod: "Versandart",
  howDelivered: "Wie soll die Bestellung ankommen?",
  pickUpOrder: "Bestellung abholen",
  store: "Abholung",
  chooseStore: "Wähle eine Abholstation in der Nähe",
  payment: "Zahlung",
  paymentMethod: "Zahlungsart",
  paymentDetails: "Zahlungsdetails",
  giftCard: "Gutschein",
  enterPaymentDetails: "Zahlungsdaten eingeben",
  continueToReview: "Weiter zur Prüfung",
  anotherStep: "Im nächsten Schritt erscheinen die Zahlungsdaten.",
  review: "Prüfen",
  placeOrder: "Bestellung absenden",
  selectPaymentMethod: "Zahlungsart wählen",
  reviewLegal:
    "Mit dem Absenden bestätigst du, dass du die Nutzungsbedingungen, Verkaufsbedingungen und Rückgaberichtlinien gelesen und akzeptiert hast und die Datenschutzerklärung zur Kenntnis genommen hast.",
  addPromotion: "Aktionscode hinzufügen",
  apply: "Anwenden",
  promotionsApplied: "Aktionscode angewendet:",
  removeDiscount: "Aktionscode entfernen",
  firstName: "Vorname",
  lastName: "Nachname",
  email: "E-Mail",
  password: "Passwort",
  phone: "Telefon",
  company: "Firma",
  address: "Adresse",
  apartment: "Adresszusatz",
  postalCode: "Postleitzahl",
  city: "Ort",
  province: "Bundesland",
  country: "Land",
  validEmail: "Bitte eine gültige E-Mail-Adresse eingeben.",
  billingSameAsShipping: "Rechnungsadresse entspricht der Lieferadresse",
  chooseAddress: "Adresse wählen",
  welcomeBack: "Willkommen zurück",
  signInAccess: "Melde dich an, um Bestellungen und Adressen zu verwalten.",
  verificationSent: (email: string) =>
    `Wir haben einen Bestätigungslink an ${email} geschickt. Bitte die E-Mail bestätigen und danach anmelden.`,
  notAMember: "Noch kein Konto?",
  joinUs: "Registrieren",
  becomeMember: "Konto anlegen",
  createProfile:
    "Lege ein Konto an, um Bestellungen zu verfolgen und den Checkout zu beschleunigen.",
  agreePrivacy: "Mit der Registrierung akzeptierst du die",
  privacyPolicy: "Datenschutzerklärung",
  and: "und das",
  termsOfUse: "Impressum",
  join: "Konto anlegen",
  alreadyMember: "Schon ein Konto?",
  hello: (name?: string | null) => `Hallo${name ? ` ${name}` : ""}`,
  signedInAs: "Angemeldet als:",
  profile: "Profil",
  completed: "Ausgefüllt",
  addresses: "Adressen",
  saved: "Gespeichert",
  recentOrders: "Letzte Bestellungen",
  datePlaced: "Bestellt am",
  orderNumber: "Bestellnummer",
  totalAmount: "Betrag",
  goToOrder: (id: number | string) => `Zur Bestellung #${id}`,
  noRecentOrders: "Keine aktuellen Bestellungen",
  overview: "Übersicht",
  orders: "Bestellungen",
  logOut: "Abmelden",
  gotQuestions: "Fragen?",
  customerServiceBody:
    "Schreib uns an info@bootlabs.de. Wir melden uns innerhalb eines Werktags.",
  customerService: "Kontakt",
  nothingHere: "Noch nichts hier",
  noOrdersYet: "Du hast noch keine Bestellungen. Das können wir ändern.",
  continueShopping: "Weiter einkaufen",
  seeDetails: "Details anzeigen",
  items: (count: number) => (count === 1 ? "Artikel" : "Artikel"),
  more: "weitere",
  thankYou: "Danke!",
  orderPlaced: "Deine Bestellung ist raus.",
  weSentConfirmation: "Die Bestätigung geht an",
  orderDate: "Bestelldatum:",
  orderStatus: "Bestellstatus:",
  paymentStatus: "Zahlungsstatus:",
  needHelp: "Hilfe nötig?",
  contact: "Kontakt",
  returnsExchanges: "Rückgabe & Austausch",
  method: "Methode",
  paidAt: "bezahlt am",
  orderSummary: "Bestellübersicht",
  emailVerification: "E-Mail-Bestätigung",
  verifyingEmail: "E-Mail wird bestätigt …",
  emailVerified: "Deine E-Mail ist bestätigt. Du kannst dich jetzt anmelden.",
  goToSignIn: "Zur Anmeldung",
  verificationInvalid:
    "Dieser Bestätigungslink ist ungültig oder abgelaufen. Melde dich an, um eine neue E-Mail zu bekommen.",
  pageNotFound: "Seite nicht gefunden",
  pageNotFoundBody: "Die aufgerufene Seite gibt es nicht.",
  goToFrontpage: "Zur Startseite",
  somethingWrong: "Da ist etwas schiefgelaufen",
  language: "Sprache:",
  shippingTo: "Lieferung nach:",
  defaultLanguage: "Standard",
  loading: "Lädt …",
  creditCard: "Kreditkarte",
  manualPayment: "Manuelle Zahlung",
  selectPlaceholder: "Auswählen …",
  oldPassword: "Altes Passwort",
  newPassword: "Neues Passwort",
  confirmPassword: "Passwort bestätigen",
  passwordHidden: "Das Passwort wird aus Sicherheitsgründen nicht angezeigt.",
  noBillingAddress: "Keine Rechnungsadresse",
  newAddress: "Neue Adresse",
  addAddress: "Adresse hinzufügen",
  editAddress: "Adresse bearbeiten",
  save: "Speichern",
  cancel: "Abbrechen",
  errorOccurred: "Es ist ein Fehler aufgetreten, bitte erneut versuchen.",
  orderId: "Bestellnummer",
  cartMismatch:
    "Beim Übernehmen des Warenkorbs ist etwas schiefgelaufen",
  transferring: "Wird übernommen …",
  runTransferAgain: "Erneut versuchen",
  unlockFreeShipping: "Kostenlosen Versand freischalten",
  freeShippingUnlocked: "Kostenloser Versand freigeschaltet!",
  onlyAway: (amount: string) => `Noch ${amount} bis zum kostenlosen Versand`,
  viewCart: "Warenkorb ansehen",
  viewProducts: "Produkte ansehen",
  categories: "Kategorien",
  collections: "Kollektionen",
  copyright: (year: number) =>
    `© ${year} Bootlabs · Software & Hardware`,
} as const
