import type { ComponentRecord, SystemPreset } from "./types"

export const DEFAULT_TAX_RATE = 19
export const PSU_RESERVE_RATIO = 1.25
export const CONFIGURATION_TTL_DAYS = 14
export const DEFAULT_BUILD_TIME_DAYS = 5
export const CUSTOM_BUILD_HANDLE = "bootlabs-custom"

export const COMPONENT_CATALOG: ComponentRecord[] = [
  {
    id: "cpu-r5-7600",
    sku: "CPU-R5-7600",
    name: "AMD Ryzen 5 7600",
    manufacturer: "AMD",
    manufacturerPartNumber: "100-100001015BOX",
    type: "cpu",
    purchasePriceCents: 14900,
    targetMarginPercent: 18,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "AM5",
      tdpWatts: 65,
      biosGeneration: "zen4",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cpu-r7-7700",
    sku: "CPU-R7-7700",
    name: "AMD Ryzen 7 7700",
    manufacturer: "AMD",
    manufacturerPartNumber: "100-100000592BOX",
    type: "cpu",
    purchasePriceCents: 22900,
    targetMarginPercent: 18,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "AM5",
      tdpWatts: 65,
      biosGeneration: "zen4",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cpu-r7-9800x3d",
    sku: "CPU-R7-9800X3D",
    name: "AMD Ryzen 7 9800X3D",
    manufacturer: "AMD",
    type: "cpu",
    purchasePriceCents: 42900,
    targetMarginPercent: 16,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "AM5",
      tdpWatts: 120,
      biosGeneration: "zen5",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cpu-i5-14400",
    sku: "CPU-I5-14400",
    name: "Intel Core i5-14400",
    manufacturer: "Intel",
    type: "cpu",
    purchasePriceCents: 17900,
    targetMarginPercent: 18,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "LGA1700",
      tdpWatts: 65,
      biosGeneration: "raptor",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "mb-b650",
    sku: "MB-B650",
    name: "B650 Gaming Mainboard",
    manufacturer: "Bootlabs",
    type: "mainboard",
    purchasePriceCents: 12900,
    targetMarginPercent: 20,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "AM5",
      ramGeneration: "DDR5",
      ramSlots: 4,
      pcieVersion: "4.0",
      has12vhpwr: false,
      biosReadyCpus: ["zen4"],
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "mb-x870",
    sku: "MB-X870",
    name: "X870 Creator Mainboard",
    manufacturer: "Bootlabs",
    type: "mainboard",
    purchasePriceCents: 24900,
    targetMarginPercent: 18,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "AM5",
      ramGeneration: "DDR5",
      ramSlots: 4,
      pcieVersion: "5.0",
      has12vhpwr: true,
      biosReadyCpus: ["zen4", "zen5"],
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "mb-b760",
    sku: "MB-B760",
    name: "B760 Intel Mainboard",
    manufacturer: "Bootlabs",
    type: "mainboard",
    purchasePriceCents: 11900,
    targetMarginPercent: 20,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      socket: "LGA1700",
      ramGeneration: "DDR5",
      ramSlots: 4,
      pcieVersion: "4.0",
      has12vhpwr: false,
      biosReadyCpus: ["raptor"],
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "ram-32-6000",
    sku: "RAM-32-6000",
    name: "32 GB DDR5-6000",
    manufacturer: "Bootlabs",
    type: "ram",
    purchasePriceCents: 7900,
    targetMarginPercent: 22,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      ramGeneration: "DDR5",
      sticks: 2,
      speedMhz: 6000,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "ram-64-6000",
    sku: "RAM-64-6000",
    name: "64 GB DDR5-6000",
    manufacturer: "Bootlabs",
    type: "ram",
    purchasePriceCents: 15900,
    targetMarginPercent: 20,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      ramGeneration: "DDR5",
      sticks: 2,
      speedMhz: 6000,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "ram-32-3200",
    sku: "RAM-32-3200",
    name: "32 GB DDR4-3200",
    manufacturer: "Bootlabs",
    type: "ram",
    purchasePriceCents: 4900,
    targetMarginPercent: 22,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      ramGeneration: "DDR4",
      sticks: 2,
      speedMhz: 3200,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "gpu-4060",
    sku: "GPU-4060",
    name: "GeForce RTX 4060 8 GB",
    manufacturer: "NVIDIA",
    type: "gpu",
    purchasePriceCents: 26900,
    targetMarginPercent: 14,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      lengthMm: 242,
      widthSlots: 2,
      tdpWatts: 115,
      powerConnector: "8pin",
      pcieVersion: "4.0",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "gpu-4070s",
    sku: "GPU-4070S",
    name: "GeForce RTX 4070 SUPER 12 GB",
    manufacturer: "NVIDIA",
    type: "gpu",
    purchasePriceCents: 54900,
    targetMarginPercent: 12,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      lengthMm: 304,
      widthSlots: 2.5,
      tdpWatts: 220,
      powerConnector: "8+8pin",
      pcieVersion: "4.0",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "gpu-5080",
    sku: "GPU-5080",
    name: "GeForce RTX 5080 16 GB",
    manufacturer: "NVIDIA",
    type: "gpu",
    purchasePriceCents: 99900,
    targetMarginPercent: 10,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      lengthMm: 332,
      widthSlots: 3,
      tdpWatts: 360,
      powerConnector: "12vhpwr",
      pcieVersion: "5.0",
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cooler-air",
    sku: "COOL-AIR",
    name: "Tower-Luftkühler 165 mm",
    manufacturer: "Bootlabs",
    type: "cooler",
    purchasePriceCents: 3500,
    targetMarginPercent: 28,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      coolerType: "air",
      heightMm: 165,
      tdpWatts: 180,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cooler-aio-240",
    sku: "COOL-AIO-240",
    name: "240 mm AIO",
    manufacturer: "Bootlabs",
    type: "cooler",
    purchasePriceCents: 7900,
    targetMarginPercent: 24,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      coolerType: "aio",
      radiatorMm: 240,
      tdpWatts: 220,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "cooler-aio-360",
    sku: "COOL-AIO-360",
    name: "360 mm AIO",
    manufacturer: "Bootlabs",
    type: "cooler",
    purchasePriceCents: 11900,
    targetMarginPercent: 22,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      coolerType: "aio",
      radiatorMm: 360,
      tdpWatts: 280,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "case-mid",
    sku: "CASE-MID",
    name: "Midi-Tower",
    manufacturer: "Bootlabs",
    type: "case",
    purchasePriceCents: 6900,
    targetMarginPercent: 26,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      maxGpuLengthMm: 360,
      maxCoolerHeightMm: 170,
      maxRadiatorMm: 360,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "case-compact",
    sku: "CASE-COMPACT",
    name: "Kompakt-Gehäuse",
    manufacturer: "Bootlabs",
    type: "case",
    purchasePriceCents: 8900,
    targetMarginPercent: 24,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      maxGpuLengthMm: 280,
      maxCoolerHeightMm: 150,
      maxRadiatorMm: 240,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "psu-650",
    sku: "PSU-650",
    name: "650 W 80+ Gold",
    manufacturer: "Bootlabs",
    type: "psu",
    purchasePriceCents: 7900,
    targetMarginPercent: 22,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      wattage: 650,
      connectors: ["8pin", "8+8pin"],
      has12vhpwr: false,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "psu-850",
    sku: "PSU-850",
    name: "850 W 80+ Gold",
    manufacturer: "Bootlabs",
    type: "psu",
    purchasePriceCents: 10900,
    targetMarginPercent: 20,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {
      wattage: 850,
      connectors: ["8pin", "8+8pin", "12vhpwr"],
      has12vhpwr: true,
    },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "ssd-1tb",
    sku: "SSD-1TB",
    name: "1 TB NVMe Gen4",
    manufacturer: "Bootlabs",
    type: "ssd",
    purchasePriceCents: 6900,
    targetMarginPercent: 22,
    taxRate: DEFAULT_TAX_RATE,
    specifications: { interface: "nvme-gen4" },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "ssd-2tb",
    sku: "SSD-2TB",
    name: "2 TB NVMe Gen4",
    manufacturer: "Bootlabs",
    type: "ssd",
    purchasePriceCents: 11900,
    targetMarginPercent: 20,
    taxRate: DEFAULT_TAX_RATE,
    specifications: { interface: "nvme-gen4" },
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "os-win11",
    sku: "OS-WIN11",
    name: "Windows 11 Home",
    manufacturer: "Microsoft",
    type: "os",
    purchasePriceCents: 10900,
    targetMarginPercent: 8,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {},
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
  {
    id: "acc-wifi",
    sku: "ACC-WIFI",
    name: "WLAN + Bluetooth",
    manufacturer: "Bootlabs",
    type: "accessory",
    purchasePriceCents: 1900,
    targetMarginPercent: 30,
    taxRate: DEFAULT_TAX_RATE,
    specifications: {},
    active: true,
    purchasable: true,
    stockStatus: "in_stock",
  },
]

export const SYSTEM_PRESETS: SystemPreset[] = [
  {
    id: "play-1080",
    handle: "bootlabs-play-1080",
    name: "Bootlabs PLAY 1080",
    tagline: "1080p, hohe FPS, festes Paket.",
    targetResolution: "1080p",
    priceCents: 129900,
    leadTimeDays: 5,
    componentIds: [
      "cpu-r5-7600",
      "mb-b650",
      "ram-32-6000",
      "gpu-4060",
      "cooler-air",
      "case-mid",
      "psu-650",
      "ssd-1tb",
      "os-win11",
    ],
    highlights: ["Ryzen 5 7600", "RTX 4060", "32 GB DDR5", "1 TB SSD"],
  },
  {
    id: "play-1440",
    handle: "bootlabs-play-1440",
    name: "Bootlabs PLAY 1440",
    tagline: "1440p ohne Kompromiss am Festpreis.",
    targetResolution: "1440p",
    priceCents: 179900,
    leadTimeDays: 6,
    componentIds: [
      "cpu-r7-7700",
      "mb-b650",
      "ram-32-6000",
      "gpu-4070s",
      "cooler-aio-240",
      "case-mid",
      "psu-850",
      "ssd-1tb",
      "os-win11",
    ],
    highlights: ["Ryzen 7 7700", "RTX 4070 SUPER", "32 GB DDR5", "1 TB SSD"],
  },
  {
    id: "play-4k",
    handle: "bootlabs-play-4k",
    name: "Bootlabs PLAY 4K",
    tagline: "4K und hohe Details, gebaut und getestet.",
    targetResolution: "4K",
    priceCents: 279900,
    leadTimeDays: 7,
    componentIds: [
      "cpu-r7-9800x3d",
      "mb-x870",
      "ram-64-6000",
      "gpu-5080",
      "cooler-aio-360",
      "case-mid",
      "psu-850",
      "ssd-2tb",
      "os-win11",
    ],
    highlights: ["Ryzen 7 9800X3D", "RTX 5080", "64 GB DDR5", "2 TB SSD"],
  },
  {
    id: "create",
    handle: "bootlabs-create",
    name: "Bootlabs CREATE",
    tagline: "Schnitt, Stream, mehrere Programme gleichzeitig.",
    targetResolution: "1440p / Content",
    priceCents: 219900,
    leadTimeDays: 6,
    componentIds: [
      "cpu-r7-7700",
      "mb-x870",
      "ram-64-6000",
      "gpu-4070s",
      "cooler-aio-360",
      "case-mid",
      "psu-850",
      "ssd-2tb",
      "os-win11",
    ],
    highlights: ["Ryzen 7 7700", "RTX 4070 SUPER", "64 GB DDR5", "2 TB SSD"],
  },
  {
    id: "refresh",
    handle: "bootlabs-refresh",
    name: "Bootlabs REFRESH",
    tagline: "Alltag, Office und leichte Spiele. Klarer Einstieg.",
    targetResolution: "1080p / Office",
    priceCents: 89900,
    leadTimeDays: 4,
    componentIds: [
      "cpu-i5-14400",
      "mb-b760",
      "ram-32-6000",
      "gpu-4060",
      "cooler-air",
      "case-mid",
      "psu-650",
      "ssd-1tb",
      "os-win11",
    ],
    highlights: ["Core i5-14400", "RTX 4060", "32 GB DDR5", "1 TB SSD"],
  },
]

export function getComponent(id: string): ComponentRecord | undefined {
  return COMPONENT_CATALOG.find((item) => item.id === id)
}

export function componentsByIds(ids: string[]): ComponentRecord[] {
  return ids
    .map((id) => getComponent(id))
    .filter((item): item is ComponentRecord => Boolean(item))
}

export function toComponentRef(item: ComponentRecord): import("./types").ComponentRef {
  return {
    id: item.id,
    type: item.type,
    sku: item.sku,
    name: item.name,
    specifications: item.specifications,
  }
}
